app/book/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, HiddenField
from wtforms.validators import DataRequired
from wtforms_components import read_only
from flask_wtf.file import FileField, FileAllowed, FileRequired
from app import images

class AddBookForm(FlaskForm):
	title = StringField('Book Title', validators=[DataRequired()])
	isbn = StringField('ISBN', validators=[DataRequired()])
	summary = StringField('Summary', validators=[DataRequired()])
	book_image = FileField('Book Image', validators=[FileRequired(), FileAllowed(images, 'Images only!')])

class SearchBookForm(FlaskForm):
	search = StringField('Search for a Book', validators=[DataRequired()])

class AddBookFromSearch(FlaskForm):
	title = HiddenField( validators=[DataRequired()])
	isbn = HiddenField( validators=[DataRequired()])
	img_filename = HiddenField( validators=[DataRequired()])
	img_url = HiddenField( validators=[DataRequired()])
	summary = HiddenField( validators=[DataRequired()])

app/book/views.py
from flask import render_template, Blueprint, request, url_for, flash, redirect, g
from flask_login import login_required, current_user
from app.models import Book, User, BookSearch
from .forms import AddBookForm, SearchBookForm, AddBookFromSearch
from app import db, images
from threading import Thread
from flask_mail import Message
from itsdangerous import URLSafeTimedSerializer
from app import app, mail
MAX_SEARCH_RESULTS = 20

book_blueprint = Blueprint('book', __name__)

def flash_errors(form):
	for field, errors in form.errors.items():
		for error in errors:
			flash(u"Error in the %s field - %s" % (getattr(form, field).label.text,error), 'info')

def send_async_email(msg):
	with app.app_context():
		mail.send(msg)

def send_email(subject, recipients, html_body):
	msg = Message(subject, recipients=recipients)
	msg.html = html_body
	thr = Thread(target=send_async_email, args=[msg])
	thr.start()	

def send_request_email(requesting_user_email, book_owner_email, book):
	confirm_serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])
	confirm_url = url_for('book.confirm_request',book=book, token=confirm_serializer.dumps(requesting_user_email, salt='email-confirmation-salt'), token2=confirm_serializer.dumps(book_owner_email, salt='email-confirmation-salt'),
        _external=True)

	deny_url = url_for('book.deny_request',book=book, token=confirm_serializer.dumps(requesting_user_email, salt='email-confirmation-salt'), token2=confirm_serializer.dumps(book_owner_email, salt='email-confirmation-salt'),
        _external=True)
    
	html = render_template('email_request_book.html',requesting_user_email=requesting_user_email, book=book, confirm_url=confirm_url, deny_url=deny_url)
    
	send_email('Someone wants your book!', [book_owner_email], html)

def send_confirm_email(requesting_user_email, book_owner_email, book):
	html = render_template('email_confirm_request.html', book_owner_email=book_owner_email, book=book)
    
	send_email("There's a book coming your way!", [requesting_user_email], html)

def send_deny_email(requesting_user_email, book_owner_email, book):
	html = render_template('email_deny_request.html', book_owner_email=book_owner_email, book=book)
    
	send_email("Sorry, the book you want can't be sent.", [requesting_user_email], html)

@book_blueprint.route('/request_book/<book>/<rUser>/<bUser>', methods=['POST'])
def request_book(book, rUser, bUser):
	send_request_email(rUser, bUser, book)
	flash('Requesting book, {}!'.format(book), 'success')
	return redirect(url_for('book.user_books'))

@book_blueprint.route('/confirm_request/<book>/<token>/<token2>')
def confirm_request(book, token, token2):
	confirm_serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])
	requesting_user_email = confirm_serializer.loads(token, salt='email-confirmation-salt')
	book_owner_email = confirm_serializer.loads(token2, salt='email-confirmation-salt')
	send_confirm_email(requesting_user_email, book_owner_email, book)
	return redirect(url_for('book.home'))

@book_blueprint.route('/deny_request/<book>/<token>/<token2>')
def deny_request(book,token, token2):
	confirm_serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])
	requesting_user_email = confirm_serializer.loads(token, salt='email-confirmation-salt')
	book_owner_email = confirm_serializer.loads(token2, salt='email-confirmation-salt')
	send_deny_email(requesting_user_email, book_owner_email, book)
	return redirect(url_for('book.home'))	


@book_blueprint.before_request
def before_request():
    g.searchform = SearchBookForm()

@book_blueprint.route('/')
def home():
	return render_template('landingpage.html')


@book_blueprint.route('/public_books')
@login_required
def public_books():
	all_public_books = Book.query.filter_by(is_public=True)
	return render_template('public_books.html', public_books = all_public_books)

@book_blueprint.route('/books')
@login_required
def user_books():
	all_user_books = Book.query.filter_by(user_id = current_user.id)
	return render_template('user_books.html', user_books = all_user_books)

#@book_blueprint.route('/add', methods=['GET', 'POST'])
#def add_book():
#	form = AddBookForm()
#	if request.method == 'POST':
#		if form.validate_on_submit():
#			filename = images.save(request.files['book_image'])
#			url = images.url(filename)
#			new_book = Book(form.title.data, form.isbn.data, current_user.id, True, filename, url)
#			db.session.add(new_book)
#			db.session.commit()
#			flash('New book, {}, added!'.format(new_book.title), 'success')
#			return redirect(url_for('book.user_books'))
#		else:
#			flash_errors(form)
#			flash('ERROR! Book was not added.', 'error')
#
#	return render_template('add_book.html', form=form)

@book_blueprint.route('/add', methods=['GET', 'POST'])
def add_book():
	form = SearchBookForm()
	if request.method == 'POST':
		if form.validate_on_submit():
			return redirect(url_for('book.add_results', query=form.search.data))
		else:
			flash_errors(form)
			flash('ERROR! Could not find book.', 'error')
	return render_template('add_book.html', form=form)

@book_blueprint.route('/add_results/<query>', methods=['GET', 'POST'])
def add_results(query):
	form = AddBookFromSearch()
	if request.method == 'POST':
		if form.validate_on_submit():
			new_book = Book(form.title.data, form.isbn.data, form.summary.data, current_user.id, True, True, form.img_filename.data, form.img_url.data)
			db.session.add(new_book)
			db.session.commit()
			flash('New book, {}, added!'.format(new_book.title), 'success')
			return redirect(url_for('book.user_books'))
		else:
			flash_errors(form)
			flash('ERROR! Book was not added.', 'error')
			return redirect(url_for('book.user_books'))

	else:
		results = BookSearch.query.whoosh_search(query, MAX_SEARCH_RESULTS).all()
		return render_template('add_book_results.html',
							query=query,
							results=results,
							form=form)

@book_blueprint.route('/search', methods=['POST'])
def search():
	form = SearchBookForm()
	if form.validate_on_submit():
		results = Book.query.whoosh_search(form.search.data, MAX_SEARCH_RESULTS).all()
		return render_template('public_books_search.html', user_books = results)
	else:
		flash_errors(form)
    	flash('ERROR! Could not find book.', 'error')

@book_blueprint.route('/book/<book_id>')
def book_details(book_id):
    book_with_user = db.session.query(Book, User).join(User).filter(Book.id == book_id).first()
    if book_with_user is not None:
        if book_with_user.Book.is_public:
            return render_template('book_details.html', book=book_with_user)
        else:
            if current_user.is_authenticated and book_with_user.Book.user_id == current_user.id:
                return render_template('book_details.html', book=book_with_user)
            else:
                flash('Error! Incorrect permissions to access this book.', 'error')
    else:
        flash('Error! Book does not exist.', 'error')
    return redirect(url_for('book.public_books'))

app/user/views.py
from flask import render_template, Blueprint, request, url_for, flash, redirect, g
from sqlalchemy.exc import IntegrityError
from flask_login import login_user, current_user, login_required, logout_user
from flask_mail import Message
from threading import Thread
from itsdangerous import URLSafeTimedSerializer
from datetime import datetime
from app.book.forms import SearchBookForm
from app.models import User
from .forms import RegisterForm, LoginForm, EmailForm, PasswordForm
from app import db, mail, app

user_blueprint = Blueprint('user', __name__)

def flask_errors(form):
	for field, errors in form.errors.items():
		for error in errors:
			flash(u"Error in the %s field - %s" % (getattr(form, field).label.text, error), 'info')

def send_async_email(msg):
	with app.app_context():
		mail.send(msg)

def send_email(subject, recipients, html_body):
	msg = Message(subject, recipients=recipients)
	msg.html = html_body
	thr = Thread(target=send_async_email, args=[msg])
	thr.start()	

def send_confirmation_email(user_email):
	confirm_serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])
    	
	confirm_url = url_for('user.confirm_email', token=confirm_serializer.dumps(user_email, salt='email-confirmation-salt'),
        _external=True)
    
	html = render_template('email_confirmation.html', confirm_url=confirm_url)
    
	send_email('Confirm Your Email Address', [user_email], html)

def send_password_reset_email(user_email):
    	password_reset_serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])
    	password_reset_url = url_for('user.reset_with_token', token = password_reset_serializer.dumps(user_email, salt='password-reset-salt'),_external=True)
    
	html = render_template('email_password_reset.html', password_reset_url=password_reset_url)
   
	send_email('Password Reset Requested', [user_email], html)

@user_blueprint.before_request
def before_request():
    g.searchform = SearchBookForm()

@user_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    	form = RegisterForm(request.form)
    	if request.method == 'POST':
        	if form.validate_on_submit():
            		try:
                		new_user = User(form.email.data, form.password.data, 1)
                		new_user.authenticated = True
                		db.session.add(new_user)
                		db.session.commit()
				login_user(new_user)

				send_confirmation_email(new_user.email)
                		flash('Thanks for registering!  Please check your email to confirm your email address.', 'success')
                		
				return redirect(url_for('book.public_books'))
            		except IntegrityError:
               			db.session.rollback()
                		flash('ERROR! Email ({}) already exists.'.format(form.email.data), 'error')
    	return render_template('register.html', form=form)


@user_blueprint.route('/login', methods=['GET', 'POST'])
def login():
	form = LoginForm(request.form)
	if request.method == 'POST':
		if form.validate_on_submit():
			user = User.query.filter_by(email=form.email.data).first()
			if user is not None and user.is_correct_password(form.password.data):
				user.authenticated = True
				user.last_logged_in = user.current_logged_in
				user.current_logged_in = datetime.now()
                		db.session.add(user)
                		db.session.commit()
                		login_user(user)
                		flash('Thanks for logging in, {}'.format(current_user.email))
                		return redirect(url_for('book.public_books'))
			else:
				flash('ERROR! Incorrect login credentials.', 'error')
	return render_template('login.html', form=form)


@user_blueprint.route('/logout')
@login_required
def logout():
    	user = current_user
    	user.authenticated = False
    	db.session.add(user)
    	db.session.commit()
    	logout_user()
    	flash('Goodbye!', 'info')
    	return redirect(url_for('user.login'))

@user_blueprint.route('/confirm/<token>')
def confirm_email(token):
    	try:
        	confirm_serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])
        	email = confirm_serializer.loads(token, salt='email-confirmation-salt', max_age=3600)
    	except:
        	flash('The confirmation link is invalid or has expired.', 'error')
        	return redirect(url_for('user.login'))
    	user = User.query.filter_by(email=email).first()
    	if user.email_confirmed:
        	flash('Account already confirmed. Please login.', 'info')
    	else:
        	user.email_confirmed = True
        	user.email_confirmed_on = datetime.now()
        	db.session.add(user)
        	db.session.commit()
        	flash('Thank you for confirming your email address!', 'success')
    	return redirect(url_for('book.public_books'))

@user_blueprint.route('/reset', methods=["GET", "POST"])
def reset():
    	form = EmailForm()
    	if form.validate_on_submit():
        	try:
            		user = User.query.filter_by(email=form.email.data).first_or_404()
        	except:
            		flash('Invalid email address!', 'error')
            		return render_template('password_reset_email.html', form=form)
        	 
        	if user.email_confirmed:
            		send_password_reset_email(user.email)
            		flash('Please check your email for a password reset link.', 'success')
        	else:
            		flash('Your email address must be confirmed before attempting a password reset.', 'error')
        	return redirect(url_for('user.login'))
 
    	return render_template('password_reset_email.html', form=form)

@user_blueprint.route('/reset/<token>', methods=["GET", "POST"])
def reset_with_token(token):
	try:
		password_reset_serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])
        	email = password_reset_serializer.loads(token, salt='password-reset-salt', max_age=3600)
    	except:
        	flash('The password reset link is invalid or has expired.', 'error')
        	return redirect(url_for('user.login'))
 
    	form = PasswordForm()
 
    	if form.validate_on_submit():
        	try:
			user = User.query.filter_by(email=email).first_or_404()
        	except:
            		flash('Invalid email address!', 'error')
            		return redirect(url_for('user.login'))
 
        	user.password_plaintext = form.password.data
        	db.session.add(user)
        	db.session.commit()
        	flash('Your password has been updated!', 'success')
        	return redirect(url_for('user.login'))
 
    	return render_template('reset_password_with_token.html', form=form, token=token)

@user_blueprint.route('/user_profile')
@login_required
def user_profile():
	return render_template('user_profile.html')

@user_blueprint.route('/email_change', methods=["GET", "POST"])
@login_required
def user_email_change():
    form = EmailForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            try:
                user_check = User.query.filter_by(email=form.email.data).first()
                if user_check is None:
                    user = current_user
                    user.email = form.email.data
                    user.email_confirmed = False
                    user.email_confirmed_on = None
                    user.email_confirmation_sent_on = datetime.now()
                    db.session.add(user)
                    db.session.commit()
                    send_confirmation_email(user.email)
                    flash('Email changed!  Please confirm your new email address (link sent to new email).', 'success')
                    return redirect(url_for('user.user_profile'))
                else:
                    flash('Sorry, that email already exists!', 'error')
            except IntegrityError:
                flash('Error! That email already exists!', 'error')
    return render_template('email_change.html', form=form)
				
@user_blueprint.route('/password_change', methods=["GET", "POST"])
@login_required
def user_password_change():
    form = PasswordForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            user = current_user
            user.password_plaintext = form.password.data
            db.session.add(user)
            db.session.commit()
            flash('Password has been updated!', 'success')
            return redirect(url_for('user.user_profile'))
 
    return render_template('password_change.html', form=form)

@user_blueprint.route('/resend_confirmation')
@login_required
def resend_email_confirmation():
    try:
        send_confirmation_email(current_user.email)
        flash('Email sent to confirm your email address.  Please check your email!', 'success')
    except IntegrityError:
        flash('Error!  Unable to send email to confirm your email address.', 'error')
 
    return redirect(url_for('user.user_profile'))

@user_blueprint.route('/admin_view_users')
@login_required
def admin_view_users():
    if current_user.role != 'admin':
        abort(403)
    else:
        users = User.query.order_by(User.id).all()
        return render_template('admin_view_users.html', users=users)
    return redirect(url_for('stocks.watch_list'))

app/templates/_form_macros.html
{% macro render_field(field) %}
 <dt>{{ field.label }}:
 <dd>{{ field(**kwargs)|safe }}
 {% if field.errors %}
   <span class="error">
   {% for error in field.errors %}
     {{ error }}
   {% endfor %}
   </span>
 {% endif %}
 </dd>
{% endmacro %}

app/templates/add_book2.html
{% extends "layout.html" %}
{% from "_form_macros.html" import render_field %}

{% block content %}
 
 
<div class="add-book">
 
<div class="page-header">
 
<h2>Add a New Book</h2>
 
  </div>
 
 
 
<form action="{{ url_for('book.add_book') }}" method="post" enctype="multipart/form-data">
    {{ form.csrf_token }}
   
<dl>
      {{ render_field(form.title, placeholder="Enter Book Title") }}
      {{ render_field(form.isbn, placeholder="Enter ISBN") }}
      {{ render_field(form.book_image) }}
    </dl>
     
    <button class="btn btn-sm btn-success" type="submit">Add Book</button>
  </form>
 
</div>
 
 
{% endblock %}

app/templates/book_details.html
{% extends "layout.html" %}
{% block content %}
 
<div class="user-profile">
  <div class="page-header">
    <h2>{{ book.Book.title }}</h2>
  </div>
 
  <div class="row">
    <div class="col-sm-4">
    {% if book.Book.image_url %}
        <img src="{{ book.Book.image_url }}" class="book-details-img" alt="{{ book.Book.image_filename }}">
    {% endif %}
      <p>ISBN: {{ book.Book.isbn }}</p>
    </div>
 <div class="col-sm-6">
   <h3> Summary: </h3> 
    <p>{{ book.Book.summary }} </p>
<hr>
      <h4> Availabile? : </h4> 
      {% if book.Book.is_available %}
        <p>Yes</p>
      {% else %}
        <p>No</p>
      {% endif %}

      <h4> Current Owner : </h4>
        <p>{{ book.User.email }}</p>
        
 {% if current_user.email == book.User.email %}
      <form>
        <input type="radio" name="status" value="public" {% if book.Book.is_public %} checked {% endif %}> Public
        <input type="radio" name="status" value="private"{% if not book.Book.is_public %} checked {% endif %} > Private
      </form> 
      {% endif%}
<br>
          {% if not current_user.email == book.User.email %}
      {% if current_user.credits == 1 %}
          <form action="{{ url_for('book.request_book', book=book.Book.title, rUser=current_user.email, bUser=book.User.email) }}" method="post" name="search"> 
            <button class="btn btn-sm btn-success" type="submit">Request this Book!</button>
          </form>
      {% endif%}
    {% endif %}
 
 </div>



  </div>
</div>
 
{% endblock %}

app/templates/book_details2.html
{% extends "layout.html" %}
{% block content %}
 
<div class="user-profile">
  <div class="page-header">
    <h2>{{ book.Book.title }}</h2>
  </div>
 
  <div class="row">
    {% if book.Book.image_url %}
    <div class = "panel panel-primary">
      <div class="panel-heading">Cover</div>
      <div class="panel-body">
        <img src="{{ book.Book.image_url }}" alt="{{ book.Book.image_filename }}">
      </div>
    </div>
    {% endif %}

    <div class="panel panel-primary">
      <div class="panel-heading">ISBN</div>
      <div class="panel-body">{{ book.Book.isbn }}</div>
    </div>
 
    <div class="panel panel-primary">
      <div class="panel-heading">Available?</div>
      {% if book.Book.is_available %}
        <div class="panel-body">Yes</div>
      {% else %}
        <div class="panel-body">No</div>
      {% endif %}
    </div>

    <div class="panel panel-primary">
      <div class="panel-heading">Public or Private</div>
      {% if book.Book.is_public %}
        <div class="panel-body">Public</div>
      {% else %}
        <div class="panel-body">Private</div>
      {% endif %}
    </div>
 
    <div class="panel panel-primary">
      <div class="panel-heading">User</div>
      <div class="panel-body">{{ book.User.email }}</div>
    </div>

    {% if not current_user.email == book.User.email %}
      {% if current_user.credits == 1 %}
          <form action="{{ url_for('book.request_book', book=book.Book.title, rUser=current_user.email, bUser=book.User.email) }}" method="post" name="search"> 
            <button class="btn btn-sm btn-success" type="submit">Request this Book!</button>
          </form>
      {% endif%}
    {% endif %}

  </div>
</div>
 
{% endblock %}

app/templates/email_change.html
{% extends "layout.html" %}
{% from "_form_macros.html" import render_field %}
 
{% block content %}
 
<div class="user-profile">
  <div class="page-header">
    <h2>Email Change</h2>
  </div>
 
  <h3>Current Email: {{ current_user.email }}</h3>
  <h3>Please enter your new email:</h3>
  <form action="{{ url_for('user.user_email_change') }}" method="POST">
  {{ form.csrf_token }}
    <dl>
      {{ render_field(form.email, placeholder="Enter New Email Address") }}
    </dl>
    <button class="btn btn-sm btn-success" type="submit">Update</button>
  </form>
</div>
 
{% endblock %}

app/templates/landingpage.html
{% extends "layout.html"%}
{% block content %}

<div id="emptybookshelf">
        <div class="jumbotron" style="margin-top:40px;">
            <h1>Explore Your Shelf</h1>
            <p>The website designed to help you trade books for FREE! Get started now and recieve a complimentary credit to start off your book trading instantly!</p>
            <p><a class="btn btn-default" role="button" href="{{ url_for('user.register') }}">Click here to register now!</a></p>
        </div>
    </div>
    <section class="features">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <h2 class="text-center">How It Works</h2>
                    <p class="text-center">Just follow 3 Easy steps to start your book sharing experience now! Have Fun exploring your shelf!</p>
                </div>
                <div class="col-md-6" style="padding-right:15px;">
                    <div class="row icon-features">
                        <div class="col-xs-4 icon-feature"><i class="glyphicon glyphicon-user"></i>
                            <p>1) Create An Account and Recieve A FREE Credit..</p>
                        </div>
                        <div class="col-xs-4 icon-feature"><i class="glyphicon glyphicon-envelope"></i>
                            <p>2) Request Books You Need from Other Members.</p>
                        </div>
                        <div class="col-xs-4 icon-feature"><i class="glyphicon glyphicon-plus"></i>
                            <p>3) Add Your Own Books to Your Book Shelf to Keep Trading.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <h2 class="text-center">People Love It!</h2>
    <blockquote>
        <p class="text-center">Stop paying for books with real money! Save your cash and start using credits. </p>
        <footer>Every Explore Your Shelf User Ever</footer>
    </blockquote>
   

{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Explore Your Shelf">
    <meta name="author" content="CB & SZ">
    <title>Explore Your Shelf</title>
    <!-- styles -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    <link rel="shortcut icon" href="http://4.bp.blogspot.com/-cVGjtSvMGos/ULY1z537kCI/AAAAAAAAAdE/y2ORczr6AmY/s1600/bookstack.png"></link>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,400italic">
    <link rel="stylesheet" href="{{ url_for('static', filename='fonts/ionicons.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/user.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/Brands.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/Login-Form-Clean.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/Registration-Form-with-Photo.css') }}">

  </head>
  <body>
    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#book-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{{ url_for('book.public_books') }}">Explore Your Shelf</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="book-navbar-collapse-1">
          <ul class="nav navbar-nav">
            {% if current_user.is_authenticated %}
              <li><a href="{{ url_for('book.user_books') }}">My Book Shelf</a></li>
              <li><a href="{{ url_for('book.add_book') }}">Add Book</a></li>
              <li><form class="navbar-form" action="{{ url_for('book.search') }}" method="post" name="search"> {{ g.searchform.hidden_tag() }}{{ g.searchform.search(placeholder="Search Available Books",class='form-control form-control') }}
                <input type="submit" class="form-control" value="Search">
                </form><li>
            {% endif %}
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if current_user.is_authenticated %}
            	  {% if current_user.role == "admin" %}
                  <li><a href="{{ url_for('user.admin_view_users') }}">View All Users (Admin)</a></li>
	              {% endif %}
              <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="">{{current_user.email}}  <span class="glyphicon glyphicon-user"></span><span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="{{ url_for('user.user_profile') }}">My Profile</a></li>
                  <li><a href="{{ url_for('user.logout') }}">Log Out</a></li>
                </ul>
              </li>
            {% else %}
              <li><a href="{{ url_for('user.register') }}">Register</a></li>
              <li><a href="{{ url_for('user.login') }}">Log In</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div><!-- /.container -->
    </nav>
    <div class="container">
      <div class="content">

        <!-- flash messages -->
        {% for error_message in get_flashed_messages(category_filter=["error"]) %}
          <div class="alert alert-danger alert-dismissible">{{ error_message }}</div>
        {% endfor %}
        {% for success_message in get_flashed_messages(category_filter=["success"]) %}
          <div class="alert alert-success alert-dismissible">{{ success_message }}</div>
        {% endfor %}
        {% for info_message in get_flashed_messages(category_filter=["info"]) %}
          <div class="alert alert-info alert-dismissible">{{ info_message }}</div>
        {% endfor %}


        <!-- child template -->
        {% block content %}
        {% endblock %}


      </div>
      <div class="brands"></div>
    <footer class="site-footer">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <h5>Explore Your Shelf © 2016</h5></div>
            </div>
        </div>
    </footer>
    </div><!-- /.container -->
    <!-- scripts -->
    <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  </body>
</html>